[package]
name = "pcr_eventlog_attestation"
version = "0.1.0"
authors = ["Arthur Gautier <baloo@superbaloo.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "5"
tss-esapi = { git="https://github.com/parallaxsecond/rust-tss-esapi", branch="master", features=["generate-bindings"] }
#tss-esapi = { path="./rust-tss-esapi/tss-esapi", features=["generate-bindings"] }
sha2 = "0.9.3"
#openssl = "0.10.33"
openssl = { git = "https://github.com/baloo/rust-openssl", branch = "baloo/openssl-300/kdf" }
#openssl = { path = '/home/baloo/dev/rust-openssl/openssl' }
clap = "2.33.3"
serde = "1.0.123"
serde_derive = "1.0.123"
serde_cbor = "0.11.1"
hex-serde = "0.1.0"
serde_json = "1.0"
url = "2.2.1"

lazy_static = "1.4.0"
rand = "0.8.3"
hex = "0.4.3"

tokio = { version = "1.2.0", features = ["full"] }
tonic = "0.4.0"
prost = "0.7.0"

[build-dependencies]
tonic-build = { version = "0.4.0", features = ["prost"] }

#[patch.crates-io]
#openssl = { path = '/home/baloo/dev/rust-openssl/openssl' }
