[package]
name = "pcr_eventlog_attestation"
version = "0.1.0"
authors = ["Arthur Gautier <baloo@superbaloo.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "5"
tss-esapi = { path="rust-tss-esapi/tss-esapi", features=["generate-bindings"] }
sha2 = "0.9.3"
openssl = "0.10.32"
